# Generated by Django 2.2.14 on 2022-01-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210924_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='PhoneNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='PhoneNumber',
            field=models.CharField(max_length=50),
        ),
    ]
